// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class XemkquahoctapTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void xemkquahoctap() {
    driver.get("https://daotao.vnu.edu.vn/dkmh/login.asp");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.findElement(By.id("txtLoginId")).click();
    driver.findElement(By.id("txtLoginId")).click();
    {
      WebElement element = driver.findElement(By.id("txtLoginId"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("txtLoginId")).click();
    driver.findElement(By.id("txtPassword")).sendKeys("2002130d");
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.id("txtLoginId")).sendKeys("20021330");
    driver.findElement(By.id("txtPassword")).sendKeys("******");
    driver.findElement(By.id("txtPassword")).click();
    driver.findElement(By.id("txtPassword")).click();
    {
      WebElement element = driver.findElement(By.id("txtPassword"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("txtPassword")).sendKeys("*******");
    driver.findElement(By.id("txtPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("PortalModule_386")).click();
  }
}
