// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class XemlchthiTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void xemlchthi() {
    driver.get("https://daotao.vnu.edu.vn/dkmh/login.asp");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.findElement(By.id("txtLoginId")).click();
    driver.findElement(By.id("divLogin")).click();
    driver.findElement(By.id("txtPassword")).click();
    driver.findElement(By.id("txtPassword")).click();
    {
      WebElement element = driver.findElement(By.id("txtPassword"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("txtPassword")).sendKeys("*********");
    driver.findElement(By.id("divLogin")).click();
    driver.findElement(By.cssSelector(".button")).click();
    driver.findElement(By.id("PortalModule_379")).click();
    driver.findElement(By.id("PortalModule_382")).click();
    driver.switchTo().frame(0);
    driver.switchTo().frame(0);
    driver.findElement(By.id("std_off_email")).click();
    driver.findElement(By.id("StdEmail")).click();
    driver.findElement(By.id("StdEmail")).click();
    driver.findElement(By.id("StdEmail")).click();
    driver.switchTo().defaultContent();
    driver.switchTo().defaultContent();
    driver.findElement(By.id("PortalModule_377")).click();
    driver.findElement(By.id("PortalModule_378")).click();
    driver.findElement(By.id("PortalModule_386")).click();
    driver.switchTo().frame(0);
    driver.switchTo().frame(0);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("tr:nth-child(2) img")).click();
    vars.put("win2239", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2239").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().frame(0);
    driver.switchTo().frame(0);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("tr:nth-child(2) img")).click();
    vars.put("win2330", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2330").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
}
